name: CI

on: [push]

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.13'
      - run: pip install poetry==1.5.1
      - run: poetry install
      - run: poetry run pre-commit run --all-files

  test:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v4
        - run: docker compose run --no-deps backend-challenge-service pytest --cov . --cov-report term-missing
